/*
Schedule Software/Config Updates

Infoblox by default does automatic software updates when they become available. Updates are applied to all on-prem hosts, physical or virtual. However, you can override and schedule the software updates. You can also defer the updates to a later date and time. You can configure up to a total of 50 deferrals (scheduled and deferred software updates), which means you have the flexibility to create up to 50 update groups across different on-prem hosts by mapping with appropriate tags. Tags are be used to associate deferrals (scheduled or deferred) with a specific or group of onprem-hosts. Apart from software update deferrals, config update deferrals also can be configured using these overrides.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upgradepolicy

import (
	"encoding/json"
)

// checks if the ServiceV2UpdateBatchMaintenanceWindow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceV2UpdateBatchMaintenanceWindow{}

// ServiceV2UpdateBatchMaintenanceWindow struct for ServiceV2UpdateBatchMaintenanceWindow
type ServiceV2UpdateBatchMaintenanceWindow struct {
	DeferredWindow       *ServiceV2DeferredWindow          `json:"deferred_window,omitempty"`
	MwId                 *string                           `json:"mw_id,omitempty"`
	ScheduledWindow      *ServiceV2ScheduledWindow         `json:"scheduled_window,omitempty"`
	Tags                 map[string]map[string]interface{} `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceV2UpdateBatchMaintenanceWindow ServiceV2UpdateBatchMaintenanceWindow

// NewServiceV2UpdateBatchMaintenanceWindow instantiates a new ServiceV2UpdateBatchMaintenanceWindow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceV2UpdateBatchMaintenanceWindow() *ServiceV2UpdateBatchMaintenanceWindow {
	this := ServiceV2UpdateBatchMaintenanceWindow{}
	return &this
}

// NewServiceV2UpdateBatchMaintenanceWindowWithDefaults instantiates a new ServiceV2UpdateBatchMaintenanceWindow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceV2UpdateBatchMaintenanceWindowWithDefaults() *ServiceV2UpdateBatchMaintenanceWindow {
	this := ServiceV2UpdateBatchMaintenanceWindow{}
	return &this
}

// GetDeferredWindow returns the DeferredWindow field value if set, zero value otherwise.
func (o *ServiceV2UpdateBatchMaintenanceWindow) GetDeferredWindow() ServiceV2DeferredWindow {
	if o == nil || IsNil(o.DeferredWindow) {
		var ret ServiceV2DeferredWindow
		return ret
	}
	return *o.DeferredWindow
}

// GetDeferredWindowOk returns a tuple with the DeferredWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2UpdateBatchMaintenanceWindow) GetDeferredWindowOk() (*ServiceV2DeferredWindow, bool) {
	if o == nil || IsNil(o.DeferredWindow) {
		return nil, false
	}
	return o.DeferredWindow, true
}

// HasDeferredWindow returns a boolean if a field has been set.
func (o *ServiceV2UpdateBatchMaintenanceWindow) HasDeferredWindow() bool {
	if o != nil && !IsNil(o.DeferredWindow) {
		return true
	}

	return false
}

// SetDeferredWindow gets a reference to the given ServiceV2DeferredWindow and assigns it to the DeferredWindow field.
func (o *ServiceV2UpdateBatchMaintenanceWindow) SetDeferredWindow(v ServiceV2DeferredWindow) {
	o.DeferredWindow = &v
}

// GetMwId returns the MwId field value if set, zero value otherwise.
func (o *ServiceV2UpdateBatchMaintenanceWindow) GetMwId() string {
	if o == nil || IsNil(o.MwId) {
		var ret string
		return ret
	}
	return *o.MwId
}

// GetMwIdOk returns a tuple with the MwId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2UpdateBatchMaintenanceWindow) GetMwIdOk() (*string, bool) {
	if o == nil || IsNil(o.MwId) {
		return nil, false
	}
	return o.MwId, true
}

// HasMwId returns a boolean if a field has been set.
func (o *ServiceV2UpdateBatchMaintenanceWindow) HasMwId() bool {
	if o != nil && !IsNil(o.MwId) {
		return true
	}

	return false
}

// SetMwId gets a reference to the given string and assigns it to the MwId field.
func (o *ServiceV2UpdateBatchMaintenanceWindow) SetMwId(v string) {
	o.MwId = &v
}

// GetScheduledWindow returns the ScheduledWindow field value if set, zero value otherwise.
func (o *ServiceV2UpdateBatchMaintenanceWindow) GetScheduledWindow() ServiceV2ScheduledWindow {
	if o == nil || IsNil(o.ScheduledWindow) {
		var ret ServiceV2ScheduledWindow
		return ret
	}
	return *o.ScheduledWindow
}

// GetScheduledWindowOk returns a tuple with the ScheduledWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2UpdateBatchMaintenanceWindow) GetScheduledWindowOk() (*ServiceV2ScheduledWindow, bool) {
	if o == nil || IsNil(o.ScheduledWindow) {
		return nil, false
	}
	return o.ScheduledWindow, true
}

// HasScheduledWindow returns a boolean if a field has been set.
func (o *ServiceV2UpdateBatchMaintenanceWindow) HasScheduledWindow() bool {
	if o != nil && !IsNil(o.ScheduledWindow) {
		return true
	}

	return false
}

// SetScheduledWindow gets a reference to the given ServiceV2ScheduledWindow and assigns it to the ScheduledWindow field.
func (o *ServiceV2UpdateBatchMaintenanceWindow) SetScheduledWindow(v ServiceV2ScheduledWindow) {
	o.ScheduledWindow = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ServiceV2UpdateBatchMaintenanceWindow) GetTags() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2UpdateBatchMaintenanceWindow) GetTagsOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ServiceV2UpdateBatchMaintenanceWindow) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]map[string]interface{} and assigns it to the Tags field.
func (o *ServiceV2UpdateBatchMaintenanceWindow) SetTags(v map[string]map[string]interface{}) {
	o.Tags = v
}

func (o ServiceV2UpdateBatchMaintenanceWindow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceV2UpdateBatchMaintenanceWindow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeferredWindow) {
		toSerialize["deferred_window"] = o.DeferredWindow
	}
	if !IsNil(o.MwId) {
		toSerialize["mw_id"] = o.MwId
	}
	if !IsNil(o.ScheduledWindow) {
		toSerialize["scheduled_window"] = o.ScheduledWindow
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceV2UpdateBatchMaintenanceWindow) UnmarshalJSON(data []byte) (err error) {
	varServiceV2UpdateBatchMaintenanceWindow := _ServiceV2UpdateBatchMaintenanceWindow{}

	err = json.Unmarshal(data, &varServiceV2UpdateBatchMaintenanceWindow)

	if err != nil {
		return err
	}

	*o = ServiceV2UpdateBatchMaintenanceWindow(varServiceV2UpdateBatchMaintenanceWindow)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "deferred_window")
		delete(additionalProperties, "mw_id")
		delete(additionalProperties, "scheduled_window")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceV2UpdateBatchMaintenanceWindow struct {
	value *ServiceV2UpdateBatchMaintenanceWindow
	isSet bool
}

func (v NullableServiceV2UpdateBatchMaintenanceWindow) Get() *ServiceV2UpdateBatchMaintenanceWindow {
	return v.value
}

func (v *NullableServiceV2UpdateBatchMaintenanceWindow) Set(val *ServiceV2UpdateBatchMaintenanceWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceV2UpdateBatchMaintenanceWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceV2UpdateBatchMaintenanceWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceV2UpdateBatchMaintenanceWindow(val *ServiceV2UpdateBatchMaintenanceWindow) *NullableServiceV2UpdateBatchMaintenanceWindow {
	return &NullableServiceV2UpdateBatchMaintenanceWindow{value: val, isSet: true}
}

func (v NullableServiceV2UpdateBatchMaintenanceWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceV2UpdateBatchMaintenanceWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
