/*
Schedule Software/Config Updates

Infoblox by default does automatic software updates when they become available. Updates are applied to all on-prem hosts, physical or virtual. However, you can override and schedule the software updates. You can also defer the updates to a later date and time. You can configure up to a total of 50 deferrals (scheduled and deferred software updates), which means you have the flexibility to create up to 50 update groups across different on-prem hosts by mapping with appropriate tags. Tags are be used to associate deferrals (scheduled or deferred) with a specific or group of onprem-hosts. Apart from software update deferrals, config update deferrals also can be configured using these overrides.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upgradepolicy

import (
	"encoding/json"
)

// checks if the ServiceV2ApplyConfigNowResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceV2ApplyConfigNowResponse{}

// ServiceV2ApplyConfigNowResponse struct for ServiceV2ApplyConfigNowResponse
type ServiceV2ApplyConfigNowResponse struct {
	Result               []ServiceV2ApplyConfigNowStatus `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceV2ApplyConfigNowResponse ServiceV2ApplyConfigNowResponse

// NewServiceV2ApplyConfigNowResponse instantiates a new ServiceV2ApplyConfigNowResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceV2ApplyConfigNowResponse() *ServiceV2ApplyConfigNowResponse {
	this := ServiceV2ApplyConfigNowResponse{}
	return &this
}

// NewServiceV2ApplyConfigNowResponseWithDefaults instantiates a new ServiceV2ApplyConfigNowResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceV2ApplyConfigNowResponseWithDefaults() *ServiceV2ApplyConfigNowResponse {
	this := ServiceV2ApplyConfigNowResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ServiceV2ApplyConfigNowResponse) GetResult() []ServiceV2ApplyConfigNowStatus {
	if o == nil || IsNil(o.Result) {
		var ret []ServiceV2ApplyConfigNowStatus
		return ret
	}
	return o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2ApplyConfigNowResponse) GetResultOk() ([]ServiceV2ApplyConfigNowStatus, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ServiceV2ApplyConfigNowResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given []ServiceV2ApplyConfigNowStatus and assigns it to the Result field.
func (o *ServiceV2ApplyConfigNowResponse) SetResult(v []ServiceV2ApplyConfigNowStatus) {
	o.Result = v
}

func (o ServiceV2ApplyConfigNowResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceV2ApplyConfigNowResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceV2ApplyConfigNowResponse) UnmarshalJSON(data []byte) (err error) {
	varServiceV2ApplyConfigNowResponse := _ServiceV2ApplyConfigNowResponse{}

	err = json.Unmarshal(data, &varServiceV2ApplyConfigNowResponse)

	if err != nil {
		return err
	}

	*o = ServiceV2ApplyConfigNowResponse(varServiceV2ApplyConfigNowResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceV2ApplyConfigNowResponse struct {
	value *ServiceV2ApplyConfigNowResponse
	isSet bool
}

func (v NullableServiceV2ApplyConfigNowResponse) Get() *ServiceV2ApplyConfigNowResponse {
	return v.value
}

func (v *NullableServiceV2ApplyConfigNowResponse) Set(val *ServiceV2ApplyConfigNowResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceV2ApplyConfigNowResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceV2ApplyConfigNowResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceV2ApplyConfigNowResponse(val *ServiceV2ApplyConfigNowResponse) *NullableServiceV2ApplyConfigNowResponse {
	return &NullableServiceV2ApplyConfigNowResponse{value: val, isSet: true}
}

func (v NullableServiceV2ApplyConfigNowResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceV2ApplyConfigNowResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
