/*
Schedule Software/Config Updates

Infoblox by default does automatic software updates when they become available. Updates are applied to all on-prem hosts, physical or virtual. However, you can override and schedule the software updates. You can also defer the updates to a later date and time. You can configure up to a total of 50 deferrals (scheduled and deferred software updates), which means you have the flexibility to create up to 50 update groups across different on-prem hosts by mapping with appropriate tags. Tags are be used to associate deferrals (scheduled or deferred) with a specific or group of onprem-hosts. Apart from software update deferrals, config update deferrals also can be configured using these overrides.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upgradepolicy

import (
	"encoding/json"
)

// checks if the ServiceV2ApplyConfigNowStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceV2ApplyConfigNowStatus{}

// ServiceV2ApplyConfigNowStatus struct for ServiceV2ApplyConfigNowStatus
type ServiceV2ApplyConfigNowStatus struct {
	Hostid               *string              `json:"hostid,omitempty"`
	Ophid                *string              `json:"ophid,omitempty"`
	StatusCode           *ServiceV2StatusCode `json:"statusCode,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceV2ApplyConfigNowStatus ServiceV2ApplyConfigNowStatus

// NewServiceV2ApplyConfigNowStatus instantiates a new ServiceV2ApplyConfigNowStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceV2ApplyConfigNowStatus() *ServiceV2ApplyConfigNowStatus {
	this := ServiceV2ApplyConfigNowStatus{}
	var statusCode ServiceV2StatusCode = SERVICEV2STATUSCODE_SUCCESS
	this.StatusCode = &statusCode
	return &this
}

// NewServiceV2ApplyConfigNowStatusWithDefaults instantiates a new ServiceV2ApplyConfigNowStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceV2ApplyConfigNowStatusWithDefaults() *ServiceV2ApplyConfigNowStatus {
	this := ServiceV2ApplyConfigNowStatus{}
	var statusCode ServiceV2StatusCode = SERVICEV2STATUSCODE_SUCCESS
	this.StatusCode = &statusCode
	return &this
}

// GetHostid returns the Hostid field value if set, zero value otherwise.
func (o *ServiceV2ApplyConfigNowStatus) GetHostid() string {
	if o == nil || IsNil(o.Hostid) {
		var ret string
		return ret
	}
	return *o.Hostid
}

// GetHostidOk returns a tuple with the Hostid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2ApplyConfigNowStatus) GetHostidOk() (*string, bool) {
	if o == nil || IsNil(o.Hostid) {
		return nil, false
	}
	return o.Hostid, true
}

// HasHostid returns a boolean if a field has been set.
func (o *ServiceV2ApplyConfigNowStatus) HasHostid() bool {
	if o != nil && !IsNil(o.Hostid) {
		return true
	}

	return false
}

// SetHostid gets a reference to the given string and assigns it to the Hostid field.
func (o *ServiceV2ApplyConfigNowStatus) SetHostid(v string) {
	o.Hostid = &v
}

// GetOphid returns the Ophid field value if set, zero value otherwise.
func (o *ServiceV2ApplyConfigNowStatus) GetOphid() string {
	if o == nil || IsNil(o.Ophid) {
		var ret string
		return ret
	}
	return *o.Ophid
}

// GetOphidOk returns a tuple with the Ophid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2ApplyConfigNowStatus) GetOphidOk() (*string, bool) {
	if o == nil || IsNil(o.Ophid) {
		return nil, false
	}
	return o.Ophid, true
}

// HasOphid returns a boolean if a field has been set.
func (o *ServiceV2ApplyConfigNowStatus) HasOphid() bool {
	if o != nil && !IsNil(o.Ophid) {
		return true
	}

	return false
}

// SetOphid gets a reference to the given string and assigns it to the Ophid field.
func (o *ServiceV2ApplyConfigNowStatus) SetOphid(v string) {
	o.Ophid = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ServiceV2ApplyConfigNowStatus) GetStatusCode() ServiceV2StatusCode {
	if o == nil || IsNil(o.StatusCode) {
		var ret ServiceV2StatusCode
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2ApplyConfigNowStatus) GetStatusCodeOk() (*ServiceV2StatusCode, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ServiceV2ApplyConfigNowStatus) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given ServiceV2StatusCode and assigns it to the StatusCode field.
func (o *ServiceV2ApplyConfigNowStatus) SetStatusCode(v ServiceV2StatusCode) {
	o.StatusCode = &v
}

func (o ServiceV2ApplyConfigNowStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceV2ApplyConfigNowStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hostid) {
		toSerialize["hostid"] = o.Hostid
	}
	if !IsNil(o.Ophid) {
		toSerialize["ophid"] = o.Ophid
	}
	if !IsNil(o.StatusCode) {
		toSerialize["statusCode"] = o.StatusCode
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceV2ApplyConfigNowStatus) UnmarshalJSON(data []byte) (err error) {
	varServiceV2ApplyConfigNowStatus := _ServiceV2ApplyConfigNowStatus{}

	err = json.Unmarshal(data, &varServiceV2ApplyConfigNowStatus)

	if err != nil {
		return err
	}

	*o = ServiceV2ApplyConfigNowStatus(varServiceV2ApplyConfigNowStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "hostid")
		delete(additionalProperties, "ophid")
		delete(additionalProperties, "statusCode")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceV2ApplyConfigNowStatus struct {
	value *ServiceV2ApplyConfigNowStatus
	isSet bool
}

func (v NullableServiceV2ApplyConfigNowStatus) Get() *ServiceV2ApplyConfigNowStatus {
	return v.value
}

func (v *NullableServiceV2ApplyConfigNowStatus) Set(val *ServiceV2ApplyConfigNowStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceV2ApplyConfigNowStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceV2ApplyConfigNowStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceV2ApplyConfigNowStatus(val *ServiceV2ApplyConfigNowStatus) *NullableServiceV2ApplyConfigNowStatus {
	return &NullableServiceV2ApplyConfigNowStatus{value: val, isSet: true}
}

func (v NullableServiceV2ApplyConfigNowStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceV2ApplyConfigNowStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
