/*
Schedule Software/Config Updates

Infoblox by default does automatic software updates when they become available. Updates are applied to all on-prem hosts, physical or virtual. However, you can override and schedule the software updates. You can also defer the updates to a later date and time. You can configure up to a total of 50 deferrals (scheduled and deferred software updates), which means you have the flexibility to create up to 50 update groups across different on-prem hosts by mapping with appropriate tags. Tags are be used to associate deferrals (scheduled or deferred) with a specific or group of onprem-hosts. Apart from software update deferrals, config update deferrals also can be configured using these overrides.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upgradepolicy

import (
	"encoding/json"
)

// checks if the ServiceV2CreateMaintenanceWindow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceV2CreateMaintenanceWindow{}

// ServiceV2CreateMaintenanceWindow struct for ServiceV2CreateMaintenanceWindow
type ServiceV2CreateMaintenanceWindow struct {
	DeferredWindow       *ServiceV2DeferredWindow          `json:"deferred_window,omitempty"`
	Id                   *string                           `json:"id,omitempty"`
	ScheduledWindow      *ServiceV2ScheduledWindow         `json:"scheduled_window,omitempty"`
	Tags                 map[string]map[string]interface{} `json:"tags,omitempty"`
	WindowType           *string                           `json:"window_type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceV2CreateMaintenanceWindow ServiceV2CreateMaintenanceWindow

// NewServiceV2CreateMaintenanceWindow instantiates a new ServiceV2CreateMaintenanceWindow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceV2CreateMaintenanceWindow() *ServiceV2CreateMaintenanceWindow {
	this := ServiceV2CreateMaintenanceWindow{}
	return &this
}

// NewServiceV2CreateMaintenanceWindowWithDefaults instantiates a new ServiceV2CreateMaintenanceWindow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceV2CreateMaintenanceWindowWithDefaults() *ServiceV2CreateMaintenanceWindow {
	this := ServiceV2CreateMaintenanceWindow{}
	return &this
}

// GetDeferredWindow returns the DeferredWindow field value if set, zero value otherwise.
func (o *ServiceV2CreateMaintenanceWindow) GetDeferredWindow() ServiceV2DeferredWindow {
	if o == nil || IsNil(o.DeferredWindow) {
		var ret ServiceV2DeferredWindow
		return ret
	}
	return *o.DeferredWindow
}

// GetDeferredWindowOk returns a tuple with the DeferredWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2CreateMaintenanceWindow) GetDeferredWindowOk() (*ServiceV2DeferredWindow, bool) {
	if o == nil || IsNil(o.DeferredWindow) {
		return nil, false
	}
	return o.DeferredWindow, true
}

// HasDeferredWindow returns a boolean if a field has been set.
func (o *ServiceV2CreateMaintenanceWindow) HasDeferredWindow() bool {
	if o != nil && !IsNil(o.DeferredWindow) {
		return true
	}

	return false
}

// SetDeferredWindow gets a reference to the given ServiceV2DeferredWindow and assigns it to the DeferredWindow field.
func (o *ServiceV2CreateMaintenanceWindow) SetDeferredWindow(v ServiceV2DeferredWindow) {
	o.DeferredWindow = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ServiceV2CreateMaintenanceWindow) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2CreateMaintenanceWindow) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ServiceV2CreateMaintenanceWindow) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ServiceV2CreateMaintenanceWindow) SetId(v string) {
	o.Id = &v
}

// GetScheduledWindow returns the ScheduledWindow field value if set, zero value otherwise.
func (o *ServiceV2CreateMaintenanceWindow) GetScheduledWindow() ServiceV2ScheduledWindow {
	if o == nil || IsNil(o.ScheduledWindow) {
		var ret ServiceV2ScheduledWindow
		return ret
	}
	return *o.ScheduledWindow
}

// GetScheduledWindowOk returns a tuple with the ScheduledWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2CreateMaintenanceWindow) GetScheduledWindowOk() (*ServiceV2ScheduledWindow, bool) {
	if o == nil || IsNil(o.ScheduledWindow) {
		return nil, false
	}
	return o.ScheduledWindow, true
}

// HasScheduledWindow returns a boolean if a field has been set.
func (o *ServiceV2CreateMaintenanceWindow) HasScheduledWindow() bool {
	if o != nil && !IsNil(o.ScheduledWindow) {
		return true
	}

	return false
}

// SetScheduledWindow gets a reference to the given ServiceV2ScheduledWindow and assigns it to the ScheduledWindow field.
func (o *ServiceV2CreateMaintenanceWindow) SetScheduledWindow(v ServiceV2ScheduledWindow) {
	o.ScheduledWindow = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ServiceV2CreateMaintenanceWindow) GetTags() map[string]map[string]interface{} {
	if o == nil || IsNil(o.Tags) {
		var ret map[string]map[string]interface{}
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2CreateMaintenanceWindow) GetTagsOk() (map[string]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Tags) {
		return map[string]map[string]interface{}{}, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ServiceV2CreateMaintenanceWindow) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]map[string]interface{} and assigns it to the Tags field.
func (o *ServiceV2CreateMaintenanceWindow) SetTags(v map[string]map[string]interface{}) {
	o.Tags = v
}

// GetWindowType returns the WindowType field value if set, zero value otherwise.
func (o *ServiceV2CreateMaintenanceWindow) GetWindowType() string {
	if o == nil || IsNil(o.WindowType) {
		var ret string
		return ret
	}
	return *o.WindowType
}

// GetWindowTypeOk returns a tuple with the WindowType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2CreateMaintenanceWindow) GetWindowTypeOk() (*string, bool) {
	if o == nil || IsNil(o.WindowType) {
		return nil, false
	}
	return o.WindowType, true
}

// HasWindowType returns a boolean if a field has been set.
func (o *ServiceV2CreateMaintenanceWindow) HasWindowType() bool {
	if o != nil && !IsNil(o.WindowType) {
		return true
	}

	return false
}

// SetWindowType gets a reference to the given string and assigns it to the WindowType field.
func (o *ServiceV2CreateMaintenanceWindow) SetWindowType(v string) {
	o.WindowType = &v
}

func (o ServiceV2CreateMaintenanceWindow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceV2CreateMaintenanceWindow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeferredWindow) {
		toSerialize["deferred_window"] = o.DeferredWindow
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ScheduledWindow) {
		toSerialize["scheduled_window"] = o.ScheduledWindow
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.WindowType) {
		toSerialize["window_type"] = o.WindowType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceV2CreateMaintenanceWindow) UnmarshalJSON(data []byte) (err error) {
	varServiceV2CreateMaintenanceWindow := _ServiceV2CreateMaintenanceWindow{}

	err = json.Unmarshal(data, &varServiceV2CreateMaintenanceWindow)

	if err != nil {
		return err
	}

	*o = ServiceV2CreateMaintenanceWindow(varServiceV2CreateMaintenanceWindow)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "deferred_window")
		delete(additionalProperties, "id")
		delete(additionalProperties, "scheduled_window")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "window_type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceV2CreateMaintenanceWindow struct {
	value *ServiceV2CreateMaintenanceWindow
	isSet bool
}

func (v NullableServiceV2CreateMaintenanceWindow) Get() *ServiceV2CreateMaintenanceWindow {
	return v.value
}

func (v *NullableServiceV2CreateMaintenanceWindow) Set(val *ServiceV2CreateMaintenanceWindow) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceV2CreateMaintenanceWindow) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceV2CreateMaintenanceWindow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceV2CreateMaintenanceWindow(val *ServiceV2CreateMaintenanceWindow) *NullableServiceV2CreateMaintenanceWindow {
	return &NullableServiceV2CreateMaintenanceWindow{value: val, isSet: true}
}

func (v NullableServiceV2CreateMaintenanceWindow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceV2CreateMaintenanceWindow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
