/*
Schedule Software/Config Updates

Infoblox by default does automatic software updates when they become available. Updates are applied to all on-prem hosts, physical or virtual. However, you can override and schedule the software updates. You can also defer the updates to a later date and time. You can configure up to a total of 50 deferrals (scheduled and deferred software updates), which means you have the flexibility to create up to 50 update groups across different on-prem hosts by mapping with appropriate tags. Tags are be used to associate deferrals (scheduled or deferred) with a specific or group of onprem-hosts. Apart from software update deferrals, config update deferrals also can be configured using these overrides.

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package upgradepolicy

import (
	"encoding/json"
)

// checks if the ServiceV2UpdateMaintenanceWindowResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceV2UpdateMaintenanceWindowResponse{}

// ServiceV2UpdateMaintenanceWindowResponse struct for ServiceV2UpdateMaintenanceWindowResponse
type ServiceV2UpdateMaintenanceWindowResponse struct {
	Result               *ServiceV2MaintenanceWindow `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServiceV2UpdateMaintenanceWindowResponse ServiceV2UpdateMaintenanceWindowResponse

// NewServiceV2UpdateMaintenanceWindowResponse instantiates a new ServiceV2UpdateMaintenanceWindowResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceV2UpdateMaintenanceWindowResponse() *ServiceV2UpdateMaintenanceWindowResponse {
	this := ServiceV2UpdateMaintenanceWindowResponse{}
	return &this
}

// NewServiceV2UpdateMaintenanceWindowResponseWithDefaults instantiates a new ServiceV2UpdateMaintenanceWindowResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceV2UpdateMaintenanceWindowResponseWithDefaults() *ServiceV2UpdateMaintenanceWindowResponse {
	this := ServiceV2UpdateMaintenanceWindowResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ServiceV2UpdateMaintenanceWindowResponse) GetResult() ServiceV2MaintenanceWindow {
	if o == nil || IsNil(o.Result) {
		var ret ServiceV2MaintenanceWindow
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceV2UpdateMaintenanceWindowResponse) GetResultOk() (*ServiceV2MaintenanceWindow, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ServiceV2UpdateMaintenanceWindowResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ServiceV2MaintenanceWindow and assigns it to the Result field.
func (o *ServiceV2UpdateMaintenanceWindowResponse) SetResult(v ServiceV2MaintenanceWindow) {
	o.Result = &v
}

func (o ServiceV2UpdateMaintenanceWindowResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceV2UpdateMaintenanceWindowResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServiceV2UpdateMaintenanceWindowResponse) UnmarshalJSON(data []byte) (err error) {
	varServiceV2UpdateMaintenanceWindowResponse := _ServiceV2UpdateMaintenanceWindowResponse{}

	err = json.Unmarshal(data, &varServiceV2UpdateMaintenanceWindowResponse)

	if err != nil {
		return err
	}

	*o = ServiceV2UpdateMaintenanceWindowResponse(varServiceV2UpdateMaintenanceWindowResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServiceV2UpdateMaintenanceWindowResponse struct {
	value *ServiceV2UpdateMaintenanceWindowResponse
	isSet bool
}

func (v NullableServiceV2UpdateMaintenanceWindowResponse) Get() *ServiceV2UpdateMaintenanceWindowResponse {
	return v.value
}

func (v *NullableServiceV2UpdateMaintenanceWindowResponse) Set(val *ServiceV2UpdateMaintenanceWindowResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceV2UpdateMaintenanceWindowResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceV2UpdateMaintenanceWindowResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceV2UpdateMaintenanceWindowResponse(val *ServiceV2UpdateMaintenanceWindowResponse) *NullableServiceV2UpdateMaintenanceWindowResponse {
	return &NullableServiceV2UpdateMaintenanceWindowResponse{value: val, isSet: true}
}

func (v NullableServiceV2UpdateMaintenanceWindowResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceV2UpdateMaintenanceWindowResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
