/*
DNS Configuration API

The DNS application is a BloxOne DDI service that provides cloud-based DNS configuration with on-prem host serving DNS protocol. It is part of the full-featured BloxOne DDI solution that enables customers the ability to deploy large numbers of protocol servers in the delivery of DNS and DHCP throughout their enterprise network.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package dns_config

import (
	"encoding/json"
	"fmt"
)

// checks if the ConfigInternalSecondary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigInternalSecondary{}

// ConfigInternalSecondary BloxOne DDI host acting as DNS secondary.
type ConfigInternalSecondary struct {
	// The resource identifier.
	Host string `json:"host"`
}

type _ConfigInternalSecondary ConfigInternalSecondary

// NewConfigInternalSecondary instantiates a new ConfigInternalSecondary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigInternalSecondary(host string) *ConfigInternalSecondary {
	this := ConfigInternalSecondary{}
	this.Host = host
	return &this
}

// NewConfigInternalSecondaryWithDefaults instantiates a new ConfigInternalSecondary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigInternalSecondaryWithDefaults() *ConfigInternalSecondary {
	this := ConfigInternalSecondary{}
	return &this
}

// GetHost returns the Host field value
func (o *ConfigInternalSecondary) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *ConfigInternalSecondary) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *ConfigInternalSecondary) SetHost(v string) {
	o.Host = v
}

func (o ConfigInternalSecondary) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigInternalSecondary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["host"] = o.Host
	return toSerialize, nil
}

func (o *ConfigInternalSecondary) UnmarshalJSON(bytes []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigInternalSecondary := _ConfigInternalSecondary{}

	err = json.Unmarshal(bytes, &varConfigInternalSecondary)

	if err != nil {
		return err
	}

	*o = ConfigInternalSecondary(varConfigInternalSecondary)

	return err
}

type NullableConfigInternalSecondary struct {
	value *ConfigInternalSecondary
	isSet bool
}

func (v NullableConfigInternalSecondary) Get() *ConfigInternalSecondary {
	return v.value
}

func (v *NullableConfigInternalSecondary) Set(val *ConfigInternalSecondary) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigInternalSecondary) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigInternalSecondary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigInternalSecondary(val *ConfigInternalSecondary) *NullableConfigInternalSecondary {
	return &NullableConfigInternalSecondary{value: val, isSet: true}
}

func (v NullableConfigInternalSecondary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigInternalSecondary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
