/*
DNS Configuration API

Testing ConvertDomainNameAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dnsconfig

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/infobloxopen/bloxone-go-client/dnsconfig"
)

func TestConvertDomainNameAPIService(t *testing.T) {

	apiClient := dnsconfig.NewAPIClient()

	t.Run("Test ConvertDomainNameAPIService Convert", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var domainName string

		resp, httpRes, err := apiClient.ConvertDomainNameAPI.Convert(context.Background(), domainName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
