/*
IPAM Federation API

Testing ConfigGenAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ipamfederation

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/infobloxopen/bloxone-go-client/ipamfederation"
)

func TestConfigGenAPIService(t *testing.T) {

	apiClient := ipamfederation.NewAPIClient()

	t.Run("Test ConfigGenAPIService Fetch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var ophid string

		resp, httpRes, err := apiClient.ConfigGenAPI.Fetch(context.Background(), ophid).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ConfigGenAPIService UpdateConfigStatus", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.ConfigGenAPI.UpdateConfigStatus(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
