/*
IPAM Federation API

The DDI IPAM Federation application enables a SaaS administrator to manage multiple IPAM systems from one central control point CSP.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipamfederation

import (
	"encoding/json"
)

// checks if the FederationListReservedBlockResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FederationListReservedBlockResponse{}

// FederationListReservedBlockResponse The response format to retrieve __ReservedBlock__ objects.
type FederationListReservedBlockResponse struct {
	// A list of ReservedBlock objects.
	Results              []FederationReservedBlock `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FederationListReservedBlockResponse FederationListReservedBlockResponse

// NewFederationListReservedBlockResponse instantiates a new FederationListReservedBlockResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFederationListReservedBlockResponse() *FederationListReservedBlockResponse {
	this := FederationListReservedBlockResponse{}
	return &this
}

// NewFederationListReservedBlockResponseWithDefaults instantiates a new FederationListReservedBlockResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFederationListReservedBlockResponseWithDefaults() *FederationListReservedBlockResponse {
	this := FederationListReservedBlockResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *FederationListReservedBlockResponse) GetResults() []FederationReservedBlock {
	if o == nil || IsNil(o.Results) {
		var ret []FederationReservedBlock
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationListReservedBlockResponse) GetResultsOk() ([]FederationReservedBlock, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *FederationListReservedBlockResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []FederationReservedBlock and assigns it to the Results field.
func (o *FederationListReservedBlockResponse) SetResults(v []FederationReservedBlock) {
	o.Results = v
}

func (o FederationListReservedBlockResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FederationListReservedBlockResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FederationListReservedBlockResponse) UnmarshalJSON(data []byte) (err error) {
	varFederationListReservedBlockResponse := _FederationListReservedBlockResponse{}

	err = json.Unmarshal(data, &varFederationListReservedBlockResponse)

	if err != nil {
		return err
	}

	*o = FederationListReservedBlockResponse(varFederationListReservedBlockResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFederationListReservedBlockResponse struct {
	value *FederationListReservedBlockResponse
	isSet bool
}

func (v NullableFederationListReservedBlockResponse) Get() *FederationListReservedBlockResponse {
	return v.value
}

func (v *NullableFederationListReservedBlockResponse) Set(val *FederationListReservedBlockResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFederationListReservedBlockResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFederationListReservedBlockResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFederationListReservedBlockResponse(val *FederationListReservedBlockResponse) *NullableFederationListReservedBlockResponse {
	return &NullableFederationListReservedBlockResponse{value: val, isSet: true}
}

func (v NullableFederationListReservedBlockResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFederationListReservedBlockResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
