/*
IPAM Federation API

The DDI IPAM Federation application enables a SaaS administrator to manage multiple IPAM systems from one central control point CSP.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipamfederation

import (
	"encoding/json"
)

// checks if the FederationCreateNextAvailableReservedBlockResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FederationCreateNextAvailableReservedBlockResponse{}

// FederationCreateNextAvailableReservedBlockResponse The response format to allocate next available __ReservedBlock__ objects.
type FederationCreateNextAvailableReservedBlockResponse struct {
	Results              []FederationReservedBlock `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FederationCreateNextAvailableReservedBlockResponse FederationCreateNextAvailableReservedBlockResponse

// NewFederationCreateNextAvailableReservedBlockResponse instantiates a new FederationCreateNextAvailableReservedBlockResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFederationCreateNextAvailableReservedBlockResponse() *FederationCreateNextAvailableReservedBlockResponse {
	this := FederationCreateNextAvailableReservedBlockResponse{}
	return &this
}

// NewFederationCreateNextAvailableReservedBlockResponseWithDefaults instantiates a new FederationCreateNextAvailableReservedBlockResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFederationCreateNextAvailableReservedBlockResponseWithDefaults() *FederationCreateNextAvailableReservedBlockResponse {
	this := FederationCreateNextAvailableReservedBlockResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *FederationCreateNextAvailableReservedBlockResponse) GetResults() []FederationReservedBlock {
	if o == nil || IsNil(o.Results) {
		var ret []FederationReservedBlock
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationCreateNextAvailableReservedBlockResponse) GetResultsOk() ([]FederationReservedBlock, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *FederationCreateNextAvailableReservedBlockResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []FederationReservedBlock and assigns it to the Results field.
func (o *FederationCreateNextAvailableReservedBlockResponse) SetResults(v []FederationReservedBlock) {
	o.Results = v
}

func (o FederationCreateNextAvailableReservedBlockResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FederationCreateNextAvailableReservedBlockResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FederationCreateNextAvailableReservedBlockResponse) UnmarshalJSON(data []byte) (err error) {
	varFederationCreateNextAvailableReservedBlockResponse := _FederationCreateNextAvailableReservedBlockResponse{}

	err = json.Unmarshal(data, &varFederationCreateNextAvailableReservedBlockResponse)

	if err != nil {
		return err
	}

	*o = FederationCreateNextAvailableReservedBlockResponse(varFederationCreateNextAvailableReservedBlockResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFederationCreateNextAvailableReservedBlockResponse struct {
	value *FederationCreateNextAvailableReservedBlockResponse
	isSet bool
}

func (v NullableFederationCreateNextAvailableReservedBlockResponse) Get() *FederationCreateNextAvailableReservedBlockResponse {
	return v.value
}

func (v *NullableFederationCreateNextAvailableReservedBlockResponse) Set(val *FederationCreateNextAvailableReservedBlockResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFederationCreateNextAvailableReservedBlockResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFederationCreateNextAvailableReservedBlockResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFederationCreateNextAvailableReservedBlockResponse(val *FederationCreateNextAvailableReservedBlockResponse) *NullableFederationCreateNextAvailableReservedBlockResponse {
	return &NullableFederationCreateNextAvailableReservedBlockResponse{value: val, isSet: true}
}

func (v NullableFederationCreateNextAvailableReservedBlockResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFederationCreateNextAvailableReservedBlockResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
