/*
IPAM Federation API

The DDI IPAM Federation application enables a SaaS administrator to manage multiple IPAM systems from one central control point CSP.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipamfederation

import (
	"encoding/json"
)

// checks if the FederationListNextAvailableOverlappingBlockResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FederationListNextAvailableOverlappingBlockResponse{}

// FederationListNextAvailableOverlappingBlockResponse The response format to list next available __OverlappingBlock__ objects.
type FederationListNextAvailableOverlappingBlockResponse struct {
	Results              []FederationOverlappingBlock `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FederationListNextAvailableOverlappingBlockResponse FederationListNextAvailableOverlappingBlockResponse

// NewFederationListNextAvailableOverlappingBlockResponse instantiates a new FederationListNextAvailableOverlappingBlockResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFederationListNextAvailableOverlappingBlockResponse() *FederationListNextAvailableOverlappingBlockResponse {
	this := FederationListNextAvailableOverlappingBlockResponse{}
	return &this
}

// NewFederationListNextAvailableOverlappingBlockResponseWithDefaults instantiates a new FederationListNextAvailableOverlappingBlockResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFederationListNextAvailableOverlappingBlockResponseWithDefaults() *FederationListNextAvailableOverlappingBlockResponse {
	this := FederationListNextAvailableOverlappingBlockResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *FederationListNextAvailableOverlappingBlockResponse) GetResults() []FederationOverlappingBlock {
	if o == nil || IsNil(o.Results) {
		var ret []FederationOverlappingBlock
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationListNextAvailableOverlappingBlockResponse) GetResultsOk() ([]FederationOverlappingBlock, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *FederationListNextAvailableOverlappingBlockResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []FederationOverlappingBlock and assigns it to the Results field.
func (o *FederationListNextAvailableOverlappingBlockResponse) SetResults(v []FederationOverlappingBlock) {
	o.Results = v
}

func (o FederationListNextAvailableOverlappingBlockResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FederationListNextAvailableOverlappingBlockResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FederationListNextAvailableOverlappingBlockResponse) UnmarshalJSON(data []byte) (err error) {
	varFederationListNextAvailableOverlappingBlockResponse := _FederationListNextAvailableOverlappingBlockResponse{}

	err = json.Unmarshal(data, &varFederationListNextAvailableOverlappingBlockResponse)

	if err != nil {
		return err
	}

	*o = FederationListNextAvailableOverlappingBlockResponse(varFederationListNextAvailableOverlappingBlockResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFederationListNextAvailableOverlappingBlockResponse struct {
	value *FederationListNextAvailableOverlappingBlockResponse
	isSet bool
}

func (v NullableFederationListNextAvailableOverlappingBlockResponse) Get() *FederationListNextAvailableOverlappingBlockResponse {
	return v.value
}

func (v *NullableFederationListNextAvailableOverlappingBlockResponse) Set(val *FederationListNextAvailableOverlappingBlockResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFederationListNextAvailableOverlappingBlockResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFederationListNextAvailableOverlappingBlockResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFederationListNextAvailableOverlappingBlockResponse(val *FederationListNextAvailableOverlappingBlockResponse) *NullableFederationListNextAvailableOverlappingBlockResponse {
	return &NullableFederationListNextAvailableOverlappingBlockResponse{value: val, isSet: true}
}

func (v NullableFederationListNextAvailableOverlappingBlockResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFederationListNextAvailableOverlappingBlockResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
