/*
IPAM Federation API

The DDI IPAM Federation application enables a SaaS administrator to manage multiple IPAM systems from one central control point CSP.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipamfederation

import (
	"encoding/json"
)

// checks if the FederationListNextAvailableReservedBlockResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FederationListNextAvailableReservedBlockResponse{}

// FederationListNextAvailableReservedBlockResponse The response format to list next available __ReservedBlock__ objects.
type FederationListNextAvailableReservedBlockResponse struct {
	Results              []FederationReservedBlock `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FederationListNextAvailableReservedBlockResponse FederationListNextAvailableReservedBlockResponse

// NewFederationListNextAvailableReservedBlockResponse instantiates a new FederationListNextAvailableReservedBlockResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFederationListNextAvailableReservedBlockResponse() *FederationListNextAvailableReservedBlockResponse {
	this := FederationListNextAvailableReservedBlockResponse{}
	return &this
}

// NewFederationListNextAvailableReservedBlockResponseWithDefaults instantiates a new FederationListNextAvailableReservedBlockResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFederationListNextAvailableReservedBlockResponseWithDefaults() *FederationListNextAvailableReservedBlockResponse {
	this := FederationListNextAvailableReservedBlockResponse{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *FederationListNextAvailableReservedBlockResponse) GetResults() []FederationReservedBlock {
	if o == nil || IsNil(o.Results) {
		var ret []FederationReservedBlock
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationListNextAvailableReservedBlockResponse) GetResultsOk() ([]FederationReservedBlock, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *FederationListNextAvailableReservedBlockResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []FederationReservedBlock and assigns it to the Results field.
func (o *FederationListNextAvailableReservedBlockResponse) SetResults(v []FederationReservedBlock) {
	o.Results = v
}

func (o FederationListNextAvailableReservedBlockResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FederationListNextAvailableReservedBlockResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FederationListNextAvailableReservedBlockResponse) UnmarshalJSON(data []byte) (err error) {
	varFederationListNextAvailableReservedBlockResponse := _FederationListNextAvailableReservedBlockResponse{}

	err = json.Unmarshal(data, &varFederationListNextAvailableReservedBlockResponse)

	if err != nil {
		return err
	}

	*o = FederationListNextAvailableReservedBlockResponse(varFederationListNextAvailableReservedBlockResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFederationListNextAvailableReservedBlockResponse struct {
	value *FederationListNextAvailableReservedBlockResponse
	isSet bool
}

func (v NullableFederationListNextAvailableReservedBlockResponse) Get() *FederationListNextAvailableReservedBlockResponse {
	return v.value
}

func (v *NullableFederationListNextAvailableReservedBlockResponse) Set(val *FederationListNextAvailableReservedBlockResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFederationListNextAvailableReservedBlockResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFederationListNextAvailableReservedBlockResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFederationListNextAvailableReservedBlockResponse(val *FederationListNextAvailableReservedBlockResponse) *NullableFederationListNextAvailableReservedBlockResponse {
	return &NullableFederationListNextAvailableReservedBlockResponse{value: val, isSet: true}
}

func (v NullableFederationListNextAvailableReservedBlockResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFederationListNextAvailableReservedBlockResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
