/*
IPAM Federation API

The DDI IPAM Federation application enables a SaaS administrator to manage multiple IPAM systems from one central control point CSP.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipamfederation

import (
	"encoding/json"
)

// checks if the FederationReadFederatedRealmResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FederationReadFederatedRealmResponse{}

// FederationReadFederatedRealmResponse The response format to retrieve the __FederatedRealm__ object.
type FederationReadFederatedRealmResponse struct {
	// The FederatedRealm object.
	Result               *FederationFederatedRealm `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FederationReadFederatedRealmResponse FederationReadFederatedRealmResponse

// NewFederationReadFederatedRealmResponse instantiates a new FederationReadFederatedRealmResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFederationReadFederatedRealmResponse() *FederationReadFederatedRealmResponse {
	this := FederationReadFederatedRealmResponse{}
	return &this
}

// NewFederationReadFederatedRealmResponseWithDefaults instantiates a new FederationReadFederatedRealmResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFederationReadFederatedRealmResponseWithDefaults() *FederationReadFederatedRealmResponse {
	this := FederationReadFederatedRealmResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *FederationReadFederatedRealmResponse) GetResult() FederationFederatedRealm {
	if o == nil || IsNil(o.Result) {
		var ret FederationFederatedRealm
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationReadFederatedRealmResponse) GetResultOk() (*FederationFederatedRealm, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *FederationReadFederatedRealmResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given FederationFederatedRealm and assigns it to the Result field.
func (o *FederationReadFederatedRealmResponse) SetResult(v FederationFederatedRealm) {
	o.Result = &v
}

func (o FederationReadFederatedRealmResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FederationReadFederatedRealmResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FederationReadFederatedRealmResponse) UnmarshalJSON(data []byte) (err error) {
	varFederationReadFederatedRealmResponse := _FederationReadFederatedRealmResponse{}

	err = json.Unmarshal(data, &varFederationReadFederatedRealmResponse)

	if err != nil {
		return err
	}

	*o = FederationReadFederatedRealmResponse(varFederationReadFederatedRealmResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFederationReadFederatedRealmResponse struct {
	value *FederationReadFederatedRealmResponse
	isSet bool
}

func (v NullableFederationReadFederatedRealmResponse) Get() *FederationReadFederatedRealmResponse {
	return v.value
}

func (v *NullableFederationReadFederatedRealmResponse) Set(val *FederationReadFederatedRealmResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableFederationReadFederatedRealmResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableFederationReadFederatedRealmResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFederationReadFederatedRealmResponse(val *FederationReadFederatedRealmResponse) *NullableFederationReadFederatedRealmResponse {
	return &NullableFederationReadFederatedRealmResponse{value: val, isSet: true}
}

func (v NullableFederationReadFederatedRealmResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFederationReadFederatedRealmResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
