/*
IPAM Federation API

The DDI IPAM Federation application enables a SaaS administrator to manage multiple IPAM systems from one central control point CSP.

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ipamfederation

import (
	"encoding/json"
)

// checks if the FederationDelegationBulkItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FederationDelegationBulkItem{}

// FederationDelegationBulkItem DelegationBulkItem object.
type FederationDelegationBulkItem struct {
	// Type of action to execute on Delegation object.  Valid values are: * _POST_ * _PATCH_ * _DELETE_
	Action *string `json:"action,omitempty"`
	// The Delegation object to execute the action on.
	Delegation           *FederationDelegation `json:"delegation,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FederationDelegationBulkItem FederationDelegationBulkItem

// NewFederationDelegationBulkItem instantiates a new FederationDelegationBulkItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFederationDelegationBulkItem() *FederationDelegationBulkItem {
	this := FederationDelegationBulkItem{}
	return &this
}

// NewFederationDelegationBulkItemWithDefaults instantiates a new FederationDelegationBulkItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFederationDelegationBulkItemWithDefaults() *FederationDelegationBulkItem {
	this := FederationDelegationBulkItem{}
	return &this
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *FederationDelegationBulkItem) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationDelegationBulkItem) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *FederationDelegationBulkItem) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *FederationDelegationBulkItem) SetAction(v string) {
	o.Action = &v
}

// GetDelegation returns the Delegation field value if set, zero value otherwise.
func (o *FederationDelegationBulkItem) GetDelegation() FederationDelegation {
	if o == nil || IsNil(o.Delegation) {
		var ret FederationDelegation
		return ret
	}
	return *o.Delegation
}

// GetDelegationOk returns a tuple with the Delegation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FederationDelegationBulkItem) GetDelegationOk() (*FederationDelegation, bool) {
	if o == nil || IsNil(o.Delegation) {
		return nil, false
	}
	return o.Delegation, true
}

// HasDelegation returns a boolean if a field has been set.
func (o *FederationDelegationBulkItem) HasDelegation() bool {
	if o != nil && !IsNil(o.Delegation) {
		return true
	}

	return false
}

// SetDelegation gets a reference to the given FederationDelegation and assigns it to the Delegation field.
func (o *FederationDelegationBulkItem) SetDelegation(v FederationDelegation) {
	o.Delegation = &v
}

func (o FederationDelegationBulkItem) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FederationDelegationBulkItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.Delegation) {
		toSerialize["delegation"] = o.Delegation
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FederationDelegationBulkItem) UnmarshalJSON(data []byte) (err error) {
	varFederationDelegationBulkItem := _FederationDelegationBulkItem{}

	err = json.Unmarshal(data, &varFederationDelegationBulkItem)

	if err != nil {
		return err
	}

	*o = FederationDelegationBulkItem(varFederationDelegationBulkItem)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "action")
		delete(additionalProperties, "delegation")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFederationDelegationBulkItem struct {
	value *FederationDelegationBulkItem
	isSet bool
}

func (v NullableFederationDelegationBulkItem) Get() *FederationDelegationBulkItem {
	return v.value
}

func (v *NullableFederationDelegationBulkItem) Set(val *FederationDelegationBulkItem) {
	v.value = val
	v.isSet = true
}

func (v NullableFederationDelegationBulkItem) IsSet() bool {
	return v.isSet
}

func (v *NullableFederationDelegationBulkItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFederationDelegationBulkItem(val *FederationDelegationBulkItem) *NullableFederationDelegationBulkItem {
	return &NullableFederationDelegationBulkItem{value: val, isSet: true}
}

func (v NullableFederationDelegationBulkItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFederationDelegationBulkItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
