/*
Discovery Configuration API V2

The Discovery configuration service is a BloxOne Service that provides configuration for accessing and syncing the Cloud assets   Base Paths:  1. provider: **_/api/cloud_discovery/v2/_**

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clouddiscovery

import (
	"encoding/json"
)

// checks if the DdidnsrickettsAccountListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DdidnsrickettsAccountListResponse{}

// DdidnsrickettsAccountListResponse The Account object List response format.
type DdidnsrickettsAccountListResponse struct {
	Page                 *ApiPageInfo            `json:"page,omitempty"`
	Results              []DdidnsrickettsAccount `json:"results,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DdidnsrickettsAccountListResponse DdidnsrickettsAccountListResponse

// NewDdidnsrickettsAccountListResponse instantiates a new DdidnsrickettsAccountListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDdidnsrickettsAccountListResponse() *DdidnsrickettsAccountListResponse {
	this := DdidnsrickettsAccountListResponse{}
	return &this
}

// NewDdidnsrickettsAccountListResponseWithDefaults instantiates a new DdidnsrickettsAccountListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDdidnsrickettsAccountListResponseWithDefaults() *DdidnsrickettsAccountListResponse {
	this := DdidnsrickettsAccountListResponse{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *DdidnsrickettsAccountListResponse) GetPage() ApiPageInfo {
	if o == nil || IsNil(o.Page) {
		var ret ApiPageInfo
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DdidnsrickettsAccountListResponse) GetPageOk() (*ApiPageInfo, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *DdidnsrickettsAccountListResponse) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given ApiPageInfo and assigns it to the Page field.
func (o *DdidnsrickettsAccountListResponse) SetPage(v ApiPageInfo) {
	o.Page = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *DdidnsrickettsAccountListResponse) GetResults() []DdidnsrickettsAccount {
	if o == nil || IsNil(o.Results) {
		var ret []DdidnsrickettsAccount
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DdidnsrickettsAccountListResponse) GetResultsOk() ([]DdidnsrickettsAccount, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *DdidnsrickettsAccountListResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []DdidnsrickettsAccount and assigns it to the Results field.
func (o *DdidnsrickettsAccountListResponse) SetResults(v []DdidnsrickettsAccount) {
	o.Results = v
}

func (o DdidnsrickettsAccountListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DdidnsrickettsAccountListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DdidnsrickettsAccountListResponse) UnmarshalJSON(data []byte) (err error) {
	varDdidnsrickettsAccountListResponse := _DdidnsrickettsAccountListResponse{}

	err = json.Unmarshal(data, &varDdidnsrickettsAccountListResponse)

	if err != nil {
		return err
	}

	*o = DdidnsrickettsAccountListResponse(varDdidnsrickettsAccountListResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "page")
		delete(additionalProperties, "results")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDdidnsrickettsAccountListResponse struct {
	value *DdidnsrickettsAccountListResponse
	isSet bool
}

func (v NullableDdidnsrickettsAccountListResponse) Get() *DdidnsrickettsAccountListResponse {
	return v.value
}

func (v *NullableDdidnsrickettsAccountListResponse) Set(val *DdidnsrickettsAccountListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDdidnsrickettsAccountListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDdidnsrickettsAccountListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDdidnsrickettsAccountListResponse(val *DdidnsrickettsAccountListResponse) *NullableDdidnsrickettsAccountListResponse {
	return &NullableDdidnsrickettsAccountListResponse{value: val, isSet: true}
}

func (v NullableDdidnsrickettsAccountListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDdidnsrickettsAccountListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
