/*
Discovery Configuration API V2

The Discovery configuration service is a BloxOne Service that provides configuration for accessing and syncing the Cloud assets   Base Paths:  1. provider: **_/api/cloud_discovery/v2/_**

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clouddiscovery

import (
	"encoding/json"
)

// checks if the DdidnsrickettsProviderReadResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DdidnsrickettsProviderReadResponse{}

// DdidnsrickettsProviderReadResponse The Provider object read response format.
type DdidnsrickettsProviderReadResponse struct {
	Result               *DdidnsrickettsDiscoveryConfig `json:"result,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DdidnsrickettsProviderReadResponse DdidnsrickettsProviderReadResponse

// NewDdidnsrickettsProviderReadResponse instantiates a new DdidnsrickettsProviderReadResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDdidnsrickettsProviderReadResponse() *DdidnsrickettsProviderReadResponse {
	this := DdidnsrickettsProviderReadResponse{}
	return &this
}

// NewDdidnsrickettsProviderReadResponseWithDefaults instantiates a new DdidnsrickettsProviderReadResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDdidnsrickettsProviderReadResponseWithDefaults() *DdidnsrickettsProviderReadResponse {
	this := DdidnsrickettsProviderReadResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *DdidnsrickettsProviderReadResponse) GetResult() DdidnsrickettsDiscoveryConfig {
	if o == nil || IsNil(o.Result) {
		var ret DdidnsrickettsDiscoveryConfig
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DdidnsrickettsProviderReadResponse) GetResultOk() (*DdidnsrickettsDiscoveryConfig, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *DdidnsrickettsProviderReadResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given DdidnsrickettsDiscoveryConfig and assigns it to the Result field.
func (o *DdidnsrickettsProviderReadResponse) SetResult(v DdidnsrickettsDiscoveryConfig) {
	o.Result = &v
}

func (o DdidnsrickettsProviderReadResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DdidnsrickettsProviderReadResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DdidnsrickettsProviderReadResponse) UnmarshalJSON(data []byte) (err error) {
	varDdidnsrickettsProviderReadResponse := _DdidnsrickettsProviderReadResponse{}

	err = json.Unmarshal(data, &varDdidnsrickettsProviderReadResponse)

	if err != nil {
		return err
	}

	*o = DdidnsrickettsProviderReadResponse(varDdidnsrickettsProviderReadResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "result")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDdidnsrickettsProviderReadResponse struct {
	value *DdidnsrickettsProviderReadResponse
	isSet bool
}

func (v NullableDdidnsrickettsProviderReadResponse) Get() *DdidnsrickettsProviderReadResponse {
	return v.value
}

func (v *NullableDdidnsrickettsProviderReadResponse) Set(val *DdidnsrickettsProviderReadResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDdidnsrickettsProviderReadResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDdidnsrickettsProviderReadResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDdidnsrickettsProviderReadResponse(val *DdidnsrickettsProviderReadResponse) *NullableDdidnsrickettsProviderReadResponse {
	return &NullableDdidnsrickettsProviderReadResponse{value: val, isSet: true}
}

func (v NullableDdidnsrickettsProviderReadResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDdidnsrickettsProviderReadResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
