/*
Discovery Configuration API V2

The Discovery configuration service is a BloxOne Service that provides configuration for accessing and syncing the Cloud assets   Base Paths:  1. provider: **_/api/cloud_discovery/v2/_**

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clouddiscovery

import (
	"encoding/json"
)

// checks if the DdidnsrickettsResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DdidnsrickettsResource{}

// DdidnsrickettsResource struct for DdidnsrickettsResource
type DdidnsrickettsResource struct {
	Excluded             *bool   `json:"excluded,omitempty"`
	Id                   *string `json:"id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _DdidnsrickettsResource DdidnsrickettsResource

// NewDdidnsrickettsResource instantiates a new DdidnsrickettsResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDdidnsrickettsResource() *DdidnsrickettsResource {
	this := DdidnsrickettsResource{}
	return &this
}

// NewDdidnsrickettsResourceWithDefaults instantiates a new DdidnsrickettsResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDdidnsrickettsResourceWithDefaults() *DdidnsrickettsResource {
	this := DdidnsrickettsResource{}
	return &this
}

// GetExcluded returns the Excluded field value if set, zero value otherwise.
func (o *DdidnsrickettsResource) GetExcluded() bool {
	if o == nil || IsNil(o.Excluded) {
		var ret bool
		return ret
	}
	return *o.Excluded
}

// GetExcludedOk returns a tuple with the Excluded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DdidnsrickettsResource) GetExcludedOk() (*bool, bool) {
	if o == nil || IsNil(o.Excluded) {
		return nil, false
	}
	return o.Excluded, true
}

// HasExcluded returns a boolean if a field has been set.
func (o *DdidnsrickettsResource) HasExcluded() bool {
	if o != nil && !IsNil(o.Excluded) {
		return true
	}

	return false
}

// SetExcluded gets a reference to the given bool and assigns it to the Excluded field.
func (o *DdidnsrickettsResource) SetExcluded(v bool) {
	o.Excluded = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *DdidnsrickettsResource) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DdidnsrickettsResource) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *DdidnsrickettsResource) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *DdidnsrickettsResource) SetId(v string) {
	o.Id = &v
}

func (o DdidnsrickettsResource) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DdidnsrickettsResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Excluded) {
		toSerialize["excluded"] = o.Excluded
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *DdidnsrickettsResource) UnmarshalJSON(data []byte) (err error) {
	varDdidnsrickettsResource := _DdidnsrickettsResource{}

	err = json.Unmarshal(data, &varDdidnsrickettsResource)

	if err != nil {
		return err
	}

	*o = DdidnsrickettsResource(varDdidnsrickettsResource)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "excluded")
		delete(additionalProperties, "id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableDdidnsrickettsResource struct {
	value *DdidnsrickettsResource
	isSet bool
}

func (v NullableDdidnsrickettsResource) Get() *DdidnsrickettsResource {
	return v.value
}

func (v *NullableDdidnsrickettsResource) Set(val *DdidnsrickettsResource) {
	v.value = val
	v.isSet = true
}

func (v NullableDdidnsrickettsResource) IsSet() bool {
	return v.isSet
}

func (v *NullableDdidnsrickettsResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDdidnsrickettsResource(val *DdidnsrickettsResource) *NullableDdidnsrickettsResource {
	return &NullableDdidnsrickettsResource{value: val, isSet: true}
}

func (v NullableDdidnsrickettsResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDdidnsrickettsResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
