/*
Infrastructure Management API

Testing DetailAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package inframgmt

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/infobloxopen/bloxone-go-client/inframgmt"
)

func TestDetailAPIService(t *testing.T) {

	apiClient := inframgmt.NewAPIClient()

	t.Run("Test DetailAPIService HostsList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DetailAPI.HostsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DetailAPIService ServicesList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DetailAPI.ServicesList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
