/*
DDI Keys API

Testing UploadAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package keys

import (
	"context"
	"github.com/infobloxopen/bloxone-go-client/client"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_keys_UploadAPIService(t *testing.T) {
	rq := require.New(t)
	c, err := client.NewAPIClient(client.Configuration{ClientName: "test"})
	rq.NoError(err)
	apiClient := c.KeysAPI

	t.Run("Test UploadAPIService UploadUpload", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.UploadAPI.UploadUpload(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
